# Generated by Django 2.2.1 on 2019-06-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=1000)),
                ('avg', models.CharField(max_length=1000)),
                ('delta', models.CharField(max_length=1000)),
                ('ratings', models.CharField(max_length=50000)),
            ],
        ),
    ]
