# Generated by Django 2.2.1 on 2019-06-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(auto_created=True, max_length=20, primary_key=True, serialize=False),
        ),
    ]
