# Generated by Django 2.2.1 on 2019-06-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownik', '0003_auto_20190601_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='genres_ordered',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
